"""milestone_2_videos

Revision ID: d993def14f93
Revises: f248a9de5f05
Create Date: 2026-07-10 06:03:35.071862
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd993def14f93'
down_revision: Union[str, None] = 'f248a9de5f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('athlete_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('camera_view', sa.String(length=20), nullable=False),
    sa.Column('processing_status', sa.Enum('pending_upload', 'uploaded', 'processing', 'completed', 'failed', name='video_processing_status', create_constraint=True), server_default='pending_upload', nullable=False),
    sa.Column('person_count_detected', sa.Integer(), nullable=True),
    sa.Column('detection_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('progress_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('annotated_video_key', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_athlete_id'), 'videos', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_videos_processing_status'), 'videos', ['processing_status'], unique=False)
    op.create_table('biomechanical_metrics',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('plane', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomechanical_metrics_video_id'), 'biomechanical_metrics', ['video_id'], unique=False)
    op.create_table('pose_frames',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('keypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'frame_number', name='uq_pose_frames_video_frame')
    )
    op.create_index(op.f('ix_pose_frames_video_id'), 'pose_frames', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pose_frames_video_id'), table_name='pose_frames')
    op.drop_table('pose_frames')
    op.drop_index(op.f('ix_biomechanical_metrics_video_id'), table_name='biomechanical_metrics')
    op.drop_table('biomechanical_metrics')
    op.drop_index(op.f('ix_videos_processing_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_athlete_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
